-- Each built-in exercise's primary and secondary muscles, stability demand, joint load
-- and how its sets are logged. Generated by scripts/exercise-attributes.ts from
-- supabase/data/exercise-attributes.json; edit the JSON, not this file. Applied by hand in
-- the SQL Editor.
--
-- Values come from the fixed vocabularies in lib/exercise-attributes.ts, enforced by
-- check constraints. Custom exercises keep empty muscle arrays (and fall back to
-- muscle_group) and are logged as weight x reps.
--
-- It is one DO block, so it applies all or nothing, and it is safe to run twice.

do $$
declare
    v_missing int;
begin
    alter table exercises add column if not exists primary_muscles text[] not null default '{}';
    alter table exercises add column if not exists secondary_muscles text[] not null default '{}';
    alter table exercises add column if not exists stability_demand text;
    alter table exercises add column if not exists joint_load jsonb;
    alter table exercises add column if not exists log_type text not null default 'weight_reps';

    alter table exercises drop constraint if exists exercises_muscles_known;
    alter table exercises add constraint exercises_muscles_known check (
        primary_muscles <@ array['chest', 'upper_chest', 'lower_chest', 'front_delts', 'side_delts', 'rear_delts', 'lats', 'upper_back', 'traps', 'lower_back', 'biceps', 'triceps', 'forearms', 'quads', 'hamstrings', 'adductors', 'calves', 'glutes', 'abductors', 'abs', 'obliques', 'cardio']::text[]
        and secondary_muscles <@ array['chest', 'upper_chest', 'lower_chest', 'front_delts', 'side_delts', 'rear_delts', 'lats', 'upper_back', 'traps', 'lower_back', 'biceps', 'triceps', 'forearms', 'quads', 'hamstrings', 'adductors', 'calves', 'glutes', 'abductors', 'abs', 'obliques', 'cardio']::text[]
    );
    alter table exercises drop constraint if exists exercises_stability_demand_known;
    alter table exercises add constraint exercises_stability_demand_known check (stability_demand in ('low', 'medium', 'high'));
    alter table exercises drop constraint if exists exercises_log_type_known;
    alter table exercises add constraint exercises_log_type_known check (log_type in ('weight_reps', 'bodyweight', 'assisted', 'duration', 'treadmill', 'cardio_level', 'rower', 'cardio_time'));

    update exercises e
    set primary_muscles = v.primary_muscles,
        secondary_muscles = v.secondary_muscles,
        stability_demand = v.stability_demand,
        joint_load = v.joint_load,
        log_type = v.log_type
    from (values
        -- Assisted Pull-up
        ('b1f735c6-9359-53d8-92ba-492d7b3b74c1', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'low', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'assisted'),
        -- Back Extension
        ('9ffc05c4-965a-5769-b0a2-3eb1c2799ec5', '{lower_back}'::text[], '{glutes,hamstrings}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'bodyweight'),
        -- Barbell Row
        ('a03bba95-1574-4ac2-a204-5e4d547711ec', '{lats,upper_back}'::text[], '{rear_delts,biceps,lower_back,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Barbell Shrug
        ('cec4fc59-2312-52cb-a4e2-68519ece446e', '{traps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Chest Supported Row
        ('835d1d13-10e5-4505-aeed-af6c2c191f79', '{upper_back,lats}'::text[], '{rear_delts,biceps,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Chin-up
        ('d9481455-4292-4125-90d5-f52a83266f5b', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'high', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Close Grip Lat Pulldown
        ('0ecb7835-60d5-416c-8f24-47cdb6bcda1f', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Shrug
        ('9a4c755e-96c2-4931-8f25-a7a243b694cf', '{traps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Inverted Row
        ('49d93e9a-1046-55ef-b402-ad802775815c', '{upper_back,lats}'::text[], '{biceps,rear_delts,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Lat Pulldown
        ('9d187d17-8fc0-477d-a9f4-779df048b0ce', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Row
        ('7203ed9a-a95b-4d51-ae97-c888dcab33dc', '{upper_back,lats}'::text[], '{biceps,rear_delts,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Meadows Row
        ('47aaeed6-f260-4b3c-b96a-75f2a48f7fcb', '{lats,upper_back}'::text[], '{rear_delts,biceps,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Pull-up
        ('305e4696-5b56-4c5f-96de-64650c61aa4b', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Rack Pull
        ('bbbb1576-240e-4692-909c-e7931c3a835b', '{lower_back,traps}'::text[], '{glutes,hamstrings,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"high","knee":"low"}'::jsonb, 'weight_reps'),
        -- Reverse Grip Lat Pulldown
        ('6861eaa4-cb70-4e80-9fab-0f8121b9cfa5', '{lats}'::text[], '{biceps,upper_back,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Seated Cable Row
        ('1b0d3a81-bf2c-4b3f-a16b-08c2eb248fb8', '{upper_back,lats}'::text[], '{biceps,rear_delts,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Single-Arm Dumbbell Row
        ('edf05050-3a02-4884-b606-e60e6a67ce6d', '{lats,upper_back}'::text[], '{biceps,rear_delts,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Straight-Arm Pulldown
        ('01cab5f1-f62c-5998-93b1-8fe221b929f8', '{lats}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- T-Bar Row
        ('8049d0df-aaec-4c33-b9b1-b4bf1000bfc4', '{upper_back,lats}'::text[], '{rear_delts,biceps,lower_back,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Wide Grip Cable Row
        ('dc1a6fe0-cded-4b62-80e6-ddd038d0f2bb', '{upper_back}'::text[], '{rear_delts,lats,biceps,forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- 21s Curl
        ('d7773d09-9253-4eb2-a8c6-5728dd9e6310', '{biceps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Barbell Curl
        ('2374ccea-4620-4458-a835-e41c34b8dfa8', '{biceps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Curl
        ('63ff7227-a29f-4d87-9e50-150affa36dd5', '{biceps}'::text[], '{forearms}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Rope Curl
        ('16da13a7-6a17-40e0-bbe0-f09dd3ef8f92', '{biceps,forearms}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Concentration Curl
        ('12346a74-b042-4634-ae08-aa23e92ca1c5', '{biceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cross Body Hammer Curl
        ('1b72bdf7-b2f8-4f3e-bb0f-44d7394de041', '{biceps,forearms}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Curl
        ('b23b42f3-4173-43c7-833b-cf3273f64c48', '{biceps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- EZ-Bar Curl
        ('6745bfa5-18d8-47dc-9e51-27d6495d21cd', '{biceps}'::text[], '{forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Hammer Curl
        ('2a67d1ba-6e6f-4b04-9c46-d436965eaf63', '{biceps,forearms}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Incline Dumbbell Curl
        ('1d2ae3f0-4130-4463-8a9f-5aefea5b4f3b', '{biceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Curl
        ('770899ef-8797-4c90-8560-912446fa755d', '{biceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Preacher Curl
        ('9ce33411-14bf-4e97-a28e-336f29738054', '{biceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Reverse Curl
        ('aaa5acad-937c-4d1a-b31d-1da00afb9caf', '{forearms}'::text[], '{biceps}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Spider Curl
        ('d60e1924-cc7a-4383-ad3a-779f2f74cee4', '{biceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Burpee
        ('316906f4-ff41-55f0-a009-e8a172caf5b0', '{cardio}'::text[], '{}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"medium","knee":"medium"}'::jsonb, 'bodyweight'),
        -- Elliptical
        ('885c345b-7f2a-4476-8211-9663d0743c7a', '{cardio}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'cardio_level'),
        -- Jump Rope
        ('64e8912e-7cdb-5abe-b6b5-4e755f5cf0c1', '{cardio}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'cardio_time'),
        -- Rowing Machine
        ('88c320b8-7d2d-4e59-bca5-312e454f7916', '{cardio}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"medium"}'::jsonb, 'rower'),
        -- Stair Climber
        ('275c314f-e01a-56d0-b139-4e1a7670a9ea', '{cardio}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'cardio_level'),
        -- Stationary Bike
        ('985ce5ab-f370-4d27-86cc-7240ef87bd2c', '{cardio}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'cardio_level'),
        -- Treadmill
        ('0a07c1a1-feef-44c3-991a-b6e3dfc1e936', '{cardio}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'treadmill'),
        -- Barbell Bench Press
        ('0f75701f-9680-43fe-ab4e-cd926fae484a', '{chest}'::text[], '{front_delts,triceps}'::text[], 'medium', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Fly
        ('97f47ef6-d55b-4c1c-929b-6b0f4cdc5e56', '{chest}'::text[], '{front_delts}'::text[], 'low', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Chest Dip Machine
        ('72de1404-e41d-423c-8a8f-43e232118b4f', '{lower_chest}'::text[], '{triceps,front_delts}'::text[], 'low', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Decline Barbell Bench Press
        ('575ee01c-ace7-5e38-a39d-3e437f8decb0', '{lower_chest}'::text[], '{triceps,front_delts}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dip
        ('39bac938-bc82-4f4f-a841-7123aa0ef080', '{lower_chest}'::text[], '{triceps,front_delts}'::text[], 'high', '{"shoulder":"high","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Dumbbell Bench Press
        ('fc16ec49-35fc-4abb-a83d-327aad08ae1c', '{chest}'::text[], '{front_delts,triceps}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Fly
        ('9d31499d-c4d3-45c9-9e00-bd82f0ad6fe6', '{chest}'::text[], '{front_delts}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Pullover
        ('36383382-f718-48da-a04b-50655b16b904', '{chest,lats}'::text[], '{triceps}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- High Cable Fly
        ('6bc596d0-db60-4b34-98e4-5167ed81d033', '{lower_chest}'::text[], '{front_delts}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Incline Barbell Bench Press
        ('08f836f6-4360-463a-bea4-ab02dfce72b7', '{upper_chest}'::text[], '{front_delts,triceps}'::text[], 'medium', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Incline Dumbbell Bench Press
        ('1749c8cc-4b91-4f9e-93fe-abf0f27343a0', '{upper_chest}'::text[], '{front_delts,triceps}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Low Cable Fly
        ('37711609-a73a-4a88-bd0f-8741535b61c6', '{upper_chest}'::text[], '{front_delts}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Chest Press
        ('27f56534-d241-55e2-9c47-b5e090946515', '{chest}'::text[], '{front_delts,triceps}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Pec Deck Fly
        ('31da5f39-7a7c-4207-9340-e70184a40121', '{chest}'::text[], '{front_delts}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Push-up
        ('0af1daea-7ae7-431a-b891-9c27f5e5a820', '{chest}'::text[], '{front_delts,triceps,abs}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Smith Machine Bench Press
        ('d420c6c5-7651-43a1-af42-4ead98d5aeb5', '{chest}'::text[], '{front_delts,triceps}'::text[], 'medium', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Svend Press
        ('75458950-ef5a-430a-a94b-d25a0e55bb56', '{chest}'::text[], '{front_delts}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Ab Machine
        ('e70512f7-cdab-4c59-ac93-2e741fbd199c', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Ab Wheel Rollout
        ('38d4887f-1427-45e6-ad98-d0cacfe7786a', '{abs}'::text[], '{obliques,lats}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'bodyweight'),
        -- Bicycle Crunch
        ('5c3a0eb4-1f1a-4c0b-b18f-0a14bfa7b461', '{abs,obliques}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Cable Crunch
        ('55b06993-12a0-444c-ba03-97e53498ec5b', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Woodchopper
        ('9bb66308-d82b-474b-9791-d4f40b01ef30', '{obliques}'::text[], '{abs}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Crunch
        ('ca181139-5ad8-5d8f-8d0c-42e99f18ac3b', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Dead Bug
        ('bc054904-5f63-4dd4-8adc-604eeb869448', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Decline Crunch
        ('03f7a98f-09d5-4f8b-b11b-08dacff1fef5', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Decline Sit Up
        ('086f76a5-c848-41fa-8ec9-5ba05be16b7d', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'bodyweight'),
        -- Dragon Flag
        ('cba26931-db80-453e-95da-652eef390c3e', '{abs}'::text[], '{obliques,lats}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"high","knee":"low"}'::jsonb, 'bodyweight'),
        -- Hanging Leg Raise
        ('585e3128-227c-4cd1-9081-2b50e8ce750a', '{abs}'::text[], '{obliques,forearms}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Hollow Body Hold
        ('649885e6-d96b-4ee6-b7e6-1255a7a4bbe7', '{abs}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'duration'),
        -- Landmine Rotation
        ('3f59c098-403f-4a79-a67b-33c5848786e2', '{obliques}'::text[], '{abs,front_delts}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Leg Raise
        ('7dfba9c8-93c0-4b8d-a7d3-8d50a4fa6b94', '{abs}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'bodyweight'),
        -- Mountain Climber
        ('bb195bba-3b13-5e43-8552-360dcc34edc9', '{abs}'::text[], '{front_delts}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Pallof Press
        ('7c9889b7-a2c3-436e-b023-d782a0632b6a', '{obliques,abs}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Plank
        ('4b7d05f8-324f-45d1-9ef3-ab6e18b8eff4', '{abs}'::text[], '{obliques}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'duration'),
        -- Russian Twist
        ('6eb701a8-c89c-4292-9ce6-15fff800a47f', '{obliques}'::text[], '{abs}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'bodyweight'),
        -- Side Plank
        ('d0fc0fac-f489-567a-a508-125d5e78c14f', '{obliques}'::text[], '{abs,abductors}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'duration'),
        -- Cable Glute Kickback
        ('35bd73ee-0bdb-4a22-8cdd-75bf9c56fb15', '{glutes}'::text[], '{hamstrings}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Pull Through
        ('0e52cb87-81ed-4d9a-9bfe-a1e8cf5f022b', '{glutes}'::text[], '{hamstrings,lower_back}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Donkey Kick
        ('2b611877-e252-4a67-b130-01abf5f17c4c', '{glutes}'::text[], '{hamstrings}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Dumbbell Hip Thrust
        ('ab765daf-8cba-443e-b55a-75bc926097e2', '{glutes}'::text[], '{hamstrings,quads}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Frog Pump
        ('520b3d4d-868a-4999-970c-a6dd4f1cfb08', '{glutes}'::text[], '{abductors}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Glute Bridge
        ('40defb75-a81b-4261-8b81-5fc6e48632fd', '{glutes}'::text[], '{hamstrings}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Hip Abduction Machine
        ('fe8ed9e9-0b54-450c-8afe-2432032a3313', '{abductors}'::text[], '{glutes}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Hip Thrust
        ('930f0373-27a4-4e41-95aa-45a5f65837f0', '{glutes}'::text[], '{hamstrings,quads}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Hip Thrust Machine
        ('4fdfcaf0-feef-4ed7-b91e-aa455795ae5b', '{glutes}'::text[], '{hamstrings}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Kettlebell Swing
        ('51231e88-fb37-5348-ae6b-5c988e2ca2af', '{glutes,hamstrings}'::text[], '{lower_back,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Monster Walk
        ('9b855917-1a27-481c-a928-a44bf8e29384', '{abductors}'::text[], '{glutes}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Barbell Back Squat
        ('cefb0269-3c0e-4d3d-9b53-ccd8c27cbdca', '{quads,glutes}'::text[], '{adductors,lower_back}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Bodyweight Squat
        ('298f7000-9b0a-5acc-b784-0b146831be61', '{quads,glutes}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Box Jump
        ('3e7225dd-f85a-4f54-9103-19889c7bafcb', '{quads,glutes}'::text[], '{calves}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"high"}'::jsonb, 'bodyweight'),
        -- Bulgarian Split Squat
        ('4aaa080b-f09d-4280-944a-499536be9c4e', '{quads,glutes}'::text[], '{adductors}'::text[], 'high', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Deadlift
        ('837efafb-516e-47de-899f-ee172486671a', '{glutes,hamstrings,lower_back}'::text[], '{quads,traps,forearms}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"high","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Front Squat
        ('351a6a17-03d3-4667-a17a-27c8b164100e', '{quads}'::text[], '{glutes,upper_back}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Glute Ham Raise
        ('7b49723c-bc70-4abc-b901-8030f90d72f6', '{hamstrings}'::text[], '{glutes,calves}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'bodyweight'),
        -- Goblet Squat
        ('d1e0a931-56f6-555c-904e-01a59cc96f3c', '{quads,glutes}'::text[], '{abs}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Good Morning
        ('540e71e6-f88c-4da1-a63d-7c691af30c39', '{hamstrings,lower_back}'::text[], '{glutes}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"high","knee":"low"}'::jsonb, 'weight_reps'),
        -- Hack Squat
        ('ca7667a9-1455-478a-afa8-c8620a18a122', '{quads}'::text[], '{glutes}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"high"}'::jsonb, 'weight_reps'),
        -- Hip Adduction Machine
        ('32921c6b-8fce-4763-89fa-431869057c49', '{adductors}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Leg Curl
        ('d161aeef-073f-41ce-890b-bf05db4c74a7', '{hamstrings}'::text[], '{calves}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Leg Extension
        ('506d4f6a-f877-46d5-8e7d-64b96071bd3f', '{quads}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Leg Press
        ('f73b69a8-15a2-4fda-8225-598c7db2940a', '{quads,glutes}'::text[], '{adductors}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Leg Press Calf Raise
        ('3a944a95-85da-4206-bc4e-ac6e11d52b0b', '{calves}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Nordic Hamstring Curl
        ('99b165ff-6298-467f-8322-61d84d5b2dd7', '{hamstrings}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'bodyweight'),
        -- Pendulum Squat
        ('fbd27bc0-3d63-4dbe-a761-fed752b3ad08', '{quads}'::text[], '{glutes}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Reverse Lunge
        ('15eb2a99-2dd6-4f35-aeb1-e55220310105', '{quads,glutes}'::text[], '{adductors,hamstrings}'::text[], 'high', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Romanian Deadlift
        ('f4f94cfd-d0b3-4153-bf4c-fe885d776dd5', '{hamstrings,glutes}'::text[], '{lower_back}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Romanian Split Squat
        ('1b8bf9ca-1a75-4b53-98fc-600bd0254185', '{glutes,quads}'::text[], '{hamstrings,adductors}'::text[], 'high', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Seated Calf Raise
        ('74ec2d18-b432-53d9-b99a-c1fb31142443', '{calves}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Sissy Squat
        ('2b3eb54f-4f4e-41c2-81a4-4623f24b483f', '{quads}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"high"}'::jsonb, 'bodyweight'),
        -- Smith Machine Squat
        ('541050a5-e32c-4856-a3c4-0e9372a5600f', '{quads,glutes}'::text[], '{adductors}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Standing Calf Raise
        ('546b7d5a-5a38-4f55-a689-05ddd45eb964', '{calves}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Step Up
        ('c7aa400c-e228-4916-bcc5-9704a506e946', '{quads,glutes}'::text[], '{hamstrings}'::text[], 'high', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Stiff Leg Deadlift
        ('56b122d2-4339-436d-8cc6-a38f74506ec0', '{hamstrings}'::text[], '{glutes,lower_back}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"high","knee":"low"}'::jsonb, 'weight_reps'),
        -- Sumo Deadlift
        ('bc7d003c-ecad-46d1-aeaf-ebe75163e883', '{glutes,adductors}'::text[], '{quads,hamstrings,lower_back}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Trap Bar Deadlift
        ('1062bc05-8db6-533a-ab8e-2a570f89b4e4', '{quads,glutes}'::text[], '{hamstrings,lower_back,traps}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"medium","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Walking Lunge
        ('564061d8-42af-42ee-8498-9e131ac582c6', '{quads,glutes}'::text[], '{adductors,hamstrings}'::text[], 'high', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"medium"}'::jsonb, 'weight_reps'),
        -- Arnold Press
        ('49d0f0d7-6f7d-4773-b35c-0aebc4c41f36', '{front_delts}'::text[], '{side_delts,triceps}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Barbell Front Raise
        ('034e4ab8-37be-4961-be59-da2294e56fb9', '{front_delts}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Behind The Neck Press
        ('a96e7f09-d250-40d6-85d5-aa34fa4d149e', '{front_delts,side_delts}'::text[], '{triceps,traps}'::text[], 'medium', '{"shoulder":"high","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Front Raise
        ('bc4a52f4-b495-49a4-9708-7f980502a690', '{front_delts}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Lateral Raise
        ('ac5ec815-d1f9-4a7d-91c7-69bcbd2ef16c', '{side_delts}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Rear Delt Fly
        ('13635d78-b011-40f6-ad52-a65bc10d3a96', '{rear_delts}'::text[], '{upper_back}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Shoulder Press
        ('88411188-ad1b-4a1b-b2b3-4e871dc65e22', '{front_delts}'::text[], '{side_delts,triceps}'::text[], 'high', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Upright Row
        ('cf4e427f-66e5-4223-9b4b-f67fade34185', '{side_delts,traps}'::text[], '{front_delts}'::text[], 'medium', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Dumbbell Y Raise
        ('52f5bfb0-b10b-4d4f-9cdf-1ff711e139d6', '{side_delts,upper_back}'::text[], '{front_delts}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Face Pull
        ('7406b9fe-5840-442e-b40d-b3f9815c29a6', '{rear_delts,upper_back}'::text[], '{traps}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Front Raise
        ('eb61023c-b340-4ee5-aa72-1c91f8a0d848', '{front_delts}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Landmine Lateral Raise
        ('11937306-35ee-4a2b-a19b-6f192715cd45', '{side_delts}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Lateral Raise
        ('ef802524-35dd-4e02-b1d3-5ceba6bf35eb', '{side_delts}'::text[], '{traps}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Lateral Raise
        ('1314c887-9309-4104-8195-b30dd29e2ed1', '{side_delts}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Shoulder Press
        ('3c0292e1-131a-4016-93b6-1bd78c24497d', '{front_delts}'::text[], '{side_delts,triceps}'::text[], 'low', '{"shoulder":"medium","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Overhead Press
        ('392382cf-432b-4f89-9162-3c5872d21880', '{front_delts}'::text[], '{side_delts,triceps,upper_chest}'::text[], 'medium', '{"shoulder":"medium","elbow":"medium","lower_back":"medium","knee":"low"}'::jsonb, 'weight_reps'),
        -- Rear Delt Fly
        ('3a63722d-62d1-44eb-8a53-b43f70443bf5', '{rear_delts}'::text[], '{upper_back}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Rear Delt Machine
        ('fe74c880-8bfd-4c0c-b050-1808ec682347', '{rear_delts}'::text[], '{upper_back}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Board Press
        ('ff7bde57-b3d9-418a-95fe-0e320bacaa0f', '{triceps}'::text[], '{chest,front_delts}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Cable Overhead Triceps Extension
        ('45731af9-c59d-4cb6-88f2-b908cf2796cd', '{triceps}'::text[], '{}'::text[], 'low', '{"shoulder":"medium","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Close-Grip Bench Press
        ('07698d2d-2e8f-4613-b703-ec0a878ca7c9', '{triceps,chest}'::text[], '{front_delts}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Diamond Push-up
        ('f3810e46-3d07-5dea-8b6b-846e22cd7a31', '{triceps}'::text[], '{chest,front_delts}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Dumbbell Kickback
        ('8ace064e-53ef-4a2c-aab4-f9211783706a', '{triceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Machine Triceps Extension
        ('ac7c512a-3634-4902-864c-74f237c96f12', '{triceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Overhead Triceps Extension
        ('cd7e3094-43f6-4650-9d50-dcfa5711613c', '{triceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"medium","elbow":"high","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Rope Pushdown
        ('4dbfd97e-2f21-4b59-b316-90cc1d9d900a', '{triceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Single Arm Cable Pushdown
        ('a386b344-3408-469f-b0e3-3ad8b6761365', '{triceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Skull Crusher
        ('8c330ae2-89db-47cf-b43f-838c7e632b90', '{triceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"high","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Tate Press
        ('1e3c3d98-1a29-4d3d-8ab2-40a8ead192b8', '{triceps}'::text[], '{}'::text[], 'medium', '{"shoulder":"low","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps'),
        -- Triceps Dip
        ('938fbadc-a757-48b9-bade-e62fc29adef5', '{triceps}'::text[], '{lower_chest,front_delts}'::text[], 'high', '{"shoulder":"high","elbow":"medium","lower_back":"low","knee":"low"}'::jsonb, 'bodyweight'),
        -- Triceps Pushdown
        ('c2da64d0-2bcb-4260-990f-8ec525601280', '{triceps}'::text[], '{}'::text[], 'low', '{"shoulder":"low","elbow":"low","lower_back":"low","knee":"low"}'::jsonb, 'weight_reps')
    ) as v (id, primary_muscles, secondary_muscles, stability_demand, joint_load, log_type)
    where e.id = v.id::uuid;

    -- Renamed exercises, and ones moved to the category of their primary muscles
    update exercises set name_zh_tw = '羅馬椅挺身' where id = '9ffc05c4-965a-5769-b0a2-3eb1c2799ec5' and name_zh_tw = '背部伸展';
    update exercises set muscle_group = 'legs' where id = '837efafb-516e-47de-899f-ee172486671a' and muscle_group = 'back';
    update exercises set muscle_group = 'legs' where id = '7b49723c-bc70-4abc-b901-8030f90d72f6' and muscle_group = 'glutes';
    update exercises set muscle_group = 'legs' where id = '1b8bf9ca-1a75-4b53-98fc-600bd0254185' and muscle_group = 'glutes';
    update exercises set muscle_group = 'legs' where id = 'bc7d003c-ecad-46d1-aeaf-ebe75163e883' and muscle_group = 'glutes';

    select count(*) into v_missing from exercises
    where not coalesce(is_custom, false) and cardinality(primary_muscles) = 0;
    if v_missing > 0 then
        raise exception '% built-in exercises have no primary muscle; the library changed since the data was written', v_missing;
    end if;
end
$$;
